### PR TITLE
Update global documents

### PR DESCRIPTION
**Pull request by cyrusguo**
Fix formatting issue on AboutUs
Add contact info for team members

### CODE REVIEW

**Comment by andrewtanJS** [comment]
Your ContactUs.adoc just needs a newline at EoF, otherwise thanks for the updating the info.

**Comment by yogtew** [comment]
Thanks for updating, can merge after a newline has been added.

**Comment by alyip98** [comment]
so uh we gonna close this or?

**Comment by andrewtanJS** [comment]
This seems like an unnecessary PR now, so I'll close it. Thanks for pointing it out @alyip98

**Pull request closed without merging**
